"""empty message

Revision ID: 641fa5fba3e1
Revises: c356a923b36f
Create Date: 2021-11-02 14:28:21.083487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '641fa5fba3e1'
down_revision = 'c356a923b36f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
